name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: "0 9 * * 1"
  workflow_dispatch:  # Allow manual triggers

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install safety bandit pip-audit semgrep detect-secrets pip-licenses
    
    - name: Run Safety check
      continue-on-error: true
      run: |
        safety check --json --output safety-report.json || true
        safety check || true
    
    - name: Run pip-audit
      continue-on-error: true
      run: |
        pip-audit --desc --format json --output pip-audit-report.json || true
        pip-audit --desc || true
    
    - name: Run Bandit
      continue-on-error: true
      run: |
        bandit -r . -f json -o bandit-report.json || true
        bandit -r . -ll || true
    
    - name: Run Semgrep
      continue-on-error: true
      run: |
        semgrep --config=p/security-audit --config=p/owasp-top-ten --json --output=semgrep-report.json . || true
        semgrep --config=p/security-audit . || true
    
    - name: Run detect-secrets
      continue-on-error: true
      run: |
        detect-secrets scan --baseline .secrets.baseline --all-files || true
    
    - name: Upload Security Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          safety-report.json
          pip-audit-report.json
          bandit-report.json
          semgrep-report.json
          .secrets.baseline
    
    - name: Upload SARIF to GitHub Security
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: semgrep-report.json
      continue-on-error: true

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/dependency-review-action@v3
      with:
        fail-on-severity: moderate
